import { collection,doc,getDoc,getDocs,limit,orderBy,query,runTransaction,serverTimestamp,Timestamp,updateDoc,where,writeBatch } from "firebase/firestore";
import { db } from "@/lib/firebase";import { normalizePhone } from "@/lib/utils";import type { Incident,IncidentType,School,Substitute,UserProfile,UserRole } from "@/types";
export async function listIncidents(max=200){const s=await getDocs(query(collection(db,"incidents"),orderBy("incidentDate","desc"),limit(max)));return s.docs.map(d=>({id:d.id,...d.data()} as Incident));}
export async function listSubstitutes(){const s=await getDocs(query(collection(db,"substitutes"),orderBy("lastIncidentAt","desc"),limit(500)));return s.docs.map(d=>({id:d.id,...d.data()} as Substitute));}
export async function listSchools(){const s=await getDocs(query(collection(db,"schools"),where("active","==",true),orderBy("schoolName")));return s.docs.map(d=>({id:d.id,...d.data()} as School));}
export async function findSubstitute(values:{bhNumber?:string;ksnNumber?:string;email?:string;phone?:string}){const checks:[string,string|undefined][]=[["bhNumber",values.bhNumber],["ksnNumber",values.ksnNumber],["emailLower",values.email?.toLowerCase()],["normalizedPhone",values.phone?normalizePhone(values.phone):undefined]];for(const [field,value] of checks){if(!value)continue;const s=await getDocs(query(collection(db,"substitutes"),where(field,"==",value),limit(1)));if(!s.empty)return{id:s.docs[0].id,...s.docs[0].data()} as Substitute;}return null;}
export interface NewIncidentInput {firstName:string;lastName:string;email?:string;phone?:string;bhNumber?:string;ksnNumber?:string;sourceRecordId?:string;schoolId?:string;schoolName:string;incidentDate:string;scheduledTime:string;incidentType:IncidentType;responseStatus:"yes"|"no"|"pending";responseDateTime?:string;responseMethod?:"phone"|"text"|"email"|"other";reasonProvided?:string;followUpNotes?:string;notes?:string}
export async function createIncident(input:NewIncidentInput,user:{uid:string;name:string}){const existing=await findSubstitute(input);const substituteRef=existing?doc(db,"substitutes",existing.id):doc(collection(db,"substitutes"));const incidentRef=doc(collection(db,"incidents"));await runTransaction(db,async tx=>{const current=existing?await tx.get(substituteRef):null;const old=current?.data();const incidentDate=Timestamp.fromDate(new Date(`${input.incidentDate}T12:00:00`));tx.set(substituteRef,{firstName:input.firstName.trim(),lastName:input.lastName.trim(),firstNameLower:input.firstName.trim().toLowerCase(),lastNameLower:input.lastName.trim().toLowerCase(),fullNameLower:`${input.firstName} ${input.lastName}`.trim().toLowerCase(),email:input.email?.trim()||null,emailLower:input.email?.trim().toLowerCase()||null,phone:input.phone?.trim()||null,normalizedPhone:input.phone?normalizePhone(input.phone):null,bhNumber:input.bhNumber?.trim()||null,ksnNumber:input.ksnNumber?.trim()||null,totalIncidents:(old?.totalIncidents??0)+1,noCallNoShowCount:(old?.noCallNoShowCount??0)+(input.incidentType==="no_call_no_show"?1:0),lateCancellationCount:(old?.lateCancellationCount??0)+(input.incidentType==="late_cancellation"?1:0),firstIncidentAt:old?.firstIncidentAt??incidentDate,lastIncidentAt:incidentDate,createdAt:old?.createdAt??serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});tx.set(incidentRef,{substituteId:substituteRef.id,substituteName:`${input.firstName} ${input.lastName}`.trim(),bhNumber:input.bhNumber||null,ksnNumber:input.ksnNumber||null,sourceRecordId:input.sourceRecordId||null,schoolId:input.schoolId||null,schoolName:input.schoolName,incidentDate,scheduledTime:input.scheduledTime,incidentType:input.incidentType,responseStatus:input.responseStatus,responseDateTime:input.responseDateTime?Timestamp.fromDate(new Date(input.responseDateTime)):null,responseMethod:input.responseMethod||null,reasonProvided:input.reasonProvided||null,followUpNotes:input.followUpNotes||null,notes:input.notes||null,createdBy:user.uid,createdByName:user.name,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});});return{substituteId:substituteRef.id,incidentId:incidentRef.id};}
export async function importedIncidentExists(sourceRecordId:string){if(!sourceRecordId)return false;const snapshot=await getDocs(query(collection(db,"incidents"),where("sourceRecordId","==",sourceRecordId),limit(1)));return!snapshot.empty;}
export async function addSchool(schoolName:string,schoolCode:string){const ref=doc(collection(db,"schools"));await writeBatch(db).set(ref,{schoolName:schoolName.trim(),schoolCode:schoolCode.trim().toUpperCase(),active:true,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}).commit();}
export async function getSettings(){const s=await getDoc(doc(db,"settings","general"));return s.exists()?s.data():{repeatOffenderThreshold:2,frequentOffenderThreshold:3,highFrequencyThreshold:4};}
export async function listUsers(){const s=await getDocs(query(collection(db,"users"),orderBy("lastName")));return s.docs.map(d=>({id:d.id,...d.data()} as UserProfile));}
export async function updateUserAccess(uid:string,role:UserRole,active:boolean){await updateDoc(doc(db,"users",uid),{role,active,updatedAt:serverTimestamp()});}
