import { readSheet } from "read-excel-file/browser";
import type { IncidentType } from "@/types";

type Cell=string|number|boolean|Date|null;
export interface ImportRow{rowNumber:number;sourceRecordId:string;firstName:string;lastName:string;email:string;ksnNumber:string;schoolName:string;incidentDate:string;incidentType:IncidentType|null;sourceNotes:string;errors:string[]}
const normalize=(value:Cell)=>String(value??"").trim();
const dateValue=(value:Cell)=>{if(value instanceof Date)return value.toISOString().slice(0,10);if(typeof value==="number"){const date=new Date(Date.UTC(1899,11,30)+value*86400000);return date.toISOString().slice(0,10)}const parsed=new Date(String(value));return Number.isNaN(parsed.getTime())?"":parsed.toISOString().slice(0,10)};
const names=(value:string)=>{const clean=value.trim();if(clean.includes(",")){const[last,first]=clean.split(",",2).map(v=>v.trim());return{firstName:first,lastName:last}}const parts=clean.split(/\s+/);return{firstName:parts[0]??"",lastName:parts.slice(1).join(" ")}};
const incidentType=(value:string):IncidentType|null=>{const normalized=value.toLowerCase().replace(/[^a-z]/g,"");if(normalized==="nocallnoshow"||normalized==="ncns")return"no_call_no_show";if(normalized==="latecancellation"||normalized==="latecancel")return"late_cancellation";return null};
export async function parseIncidentWorkbook(file:File){const rows=await readSheet(file) as Cell[][];if(rows.length<2)throw new Error("The workbook has no data rows.");const headers=rows[0].map((cell:Cell)=>normalize(cell).toLowerCase());const index=(...labels:string[])=>{for(const label of labels){const found=headers.indexOf(label);if(found>=0)return found}return-1};const columns={record:index("confirmation #","confirmation number","number"),type:index("subcategory","incident type"),school:index("school information","school"),date:index("date of ncns","incident date"),name:index("talent name","substitute","substitute name"),email:index("email"),ksn:index("ksn id","ksn number"),district:index("district"),state:index("state"),channel:index("channel")};const required=[columns.type,columns.school,columns.date,columns.name];if(required.some(value=>value<0))throw new Error("Required columns are missing: Subcategory, School Information, Date of NCNS, or Talent Name.");return rows.slice(1).filter((row:Cell[])=>row.some(Boolean)).map((row:Cell[],rowIndex:number)=>{const fullName=normalize(row[columns.name]);const parsedName=names(fullName);const type=incidentType(normalize(row[columns.type]));const schoolName=normalize(row[columns.school]);const date=dateValue(row[columns.date]);const errors:string[]=[];if(!parsedName.firstName||!parsedName.lastName)errors.push("Full substitute name is required");if(!schoolName)errors.push("School is required");if(!date)errors.push("Valid incident date is required");if(!type)errors.push("Incident type must be No Call No Show or Late Cancellation");const details=[["District",columns.district>=0?normalize(row[columns.district]):""],["State",columns.state>=0?normalize(row[columns.state]):""],["Channel",columns.channel>=0?normalize(row[columns.channel]):""]].filter(([,value])=>value).map(([label,value])=>`${label}: ${value}`).join(" · ");return{rowNumber:rowIndex+2,sourceRecordId:columns.record>=0?normalize(row[columns.record]):"",...parsedName,email:columns.email>=0?normalize(row[columns.email]):"",ksnNumber:columns.ksn>=0?normalize(row[columns.ksn]).replace(/^\(/,""):"",schoolName,incidentDate:date,incidentType:type,sourceNotes:details,errors}})}
