import type { ButtonHTMLAttributes,HTMLAttributes,InputHTMLAttributes,SelectHTMLAttributes,TextareaHTMLAttributes } from "react";import { cn } from "@/lib/utils";
export function Button({className,...p}:ButtonHTMLAttributes<HTMLButtonElement>){return <button className={cn("inline-flex h-10 items-center justify-center rounded-lg bg-primary px-4 text-sm font-semibold text-white shadow-sm transition hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-50",className)} {...p}/>}
export function Card({className,...p}:HTMLAttributes<HTMLDivElement>){return <div className={cn("rounded-xl border border-border bg-card shadow-sm",className)} {...p}/>}
export function Input({className,...p}:InputHTMLAttributes<HTMLInputElement>){return <input className={cn("h-10 w-full rounded-lg border border-input bg-white px-3 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15",className)} {...p}/>}
export function Select({className,...p}:SelectHTMLAttributes<HTMLSelectElement>){return <select className={cn("h-10 w-full rounded-lg border border-input bg-white px-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/15",className)} {...p}/>}
export function Textarea({className,...p}:TextareaHTMLAttributes<HTMLTextAreaElement>){return <textarea className={cn("min-h-24 w-full rounded-lg border border-input bg-white px-3 py-2 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/15",className)} {...p}/>}
export function Badge({className,...p}:HTMLAttributes<HTMLSpanElement>){return <span className={cn("inline-flex rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700",className)} {...p}/>}
export function Field({label,required,children}:{label:string;required?:boolean;children:React.ReactNode}){return <label className="grid gap-1.5 text-sm font-medium text-foreground"><span>{label}{required?<span className="text-danger"> *</span>:null}</span>{children}</label>}
export function PageHeader({title,description,action}:{title:string;description:string;action?:React.ReactNode}){return <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-bold tracking-tight">{title}</h1><p className="mt-1 text-sm text-muted">{description}</p></div>{action}</div>}
export function Empty({title,body}:{title:string;body:string}){return <div className="grid min-h-52 place-items-center rounded-xl border border-dashed bg-white p-8 text-center"><div><p className="font-semibold">{title}</p><p className="mt-1 text-sm text-muted">{body}</p></div></div>}
